<?xml version="1.0" encoding="UTF-8"?>
<source package="org.ojalgo">
  <class name="RecoverableCondition" extends="Exception" startLine="24">
    <javadoc>
      <text>* Something that potentially could go wrong, actually did go wrong. The API
 * user is expected to recover and continue execution. Is always declared to be
 * thrown, and must be caught.</text>
      <author>apete</author>
    </javadoc>
    <method type="constructor" name="RecoverableCondition" startLine="33" endLine="35" />
    <method type="constructor" name="RecoverableCondition" startLine="38" endLine="40" />
    <method type="String" name="toString" startLine="43" endLine="47">
      <declaration type="String" name="retVal" />
      <declaration type="String" name="tmpMessage" />
    </method>
  </class>
</source>
