<?xml version="1.0" encoding="UTF-8"?>
    <source package="org.ojalgo">
        <class name="RecoverableCondition" line="2">
            <extends class="Exception"/>
            <javadoc line="2">
                Something that potentially could go wrong, actually did go wrong. The API
                  user is expected to recover and continue execution. Is always declared to be
                  thrown, and must be caught.                
                <author>
                    apete                    
                </author>
            </javadoc>
            <method name="RecoverableCondition" type="constructor" line="9">
                <params>
                    <param name="description" type="String"/>
                </params>
            </method>
            <method name="RecoverableCondition" type="constructor" line="12"/>
            <method name="toString" type="String" line="15">
                <declaration name="retVal" type="String" line="16"/>
                <declaration name="tmpMessage" type="String" line="17"/>
            </method>
        </class>
    </source>