<?xml version="1.0" encoding="UTF-8"?>
    <source package="org.ojalgo">
        <class name="RecoverableCondition" extends="Exception" line="24">
            <javadoc line="24">
                Something that potentially could go wrong, actually did go wrong. The API
                 * user is expected to recover and continue execution. Is always declared to be
                 * thrown, and must be caught.                
                <@author>
                    r apete                    
                </@author>
            </javadoc>
            <method name="RecoverableCondition" type="constructor" line="33"/>
            <method name="RecoverableCondition" type="constructor" line="38"/>
            <method name="toString" type="String" line="43">
                <declaration name="retVal" type="String" line="44"/>
                <declaration name="tmpMessage" type="String" line="45"/>
            </method>
        </class>
    </source>